import { Router, type Request } from "express";
import { requireAuth } from "../middleware/requireAuth.js";
import { prisma } from "../prisma.js";
import { parseOptionalText } from "../lib/sparkSavings.js";

const router = Router();
router.use(requireAuth);
const uid = (req: Request) => req.user?.id ?? "";
const actorLabel = (req: Request) => req.user?.displayName || req.user?.username || "不明なユーザー";
const json = (value: unknown) => JSON.parse(JSON.stringify(value));
const date = (value: unknown, label: string, optional = false) => { if (optional && (value === null || value === undefined || value === "")) return null; if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error(`${label}を確認してください`); const parsed = new Date(`${value}T00:00:00.000Z`); if (parsed.toISOString().slice(0, 10) !== value) throw new Error(`${label}を確認してください`); return parsed; };
const integer = (value: unknown, min: number, max: number, label: string) => { const parsed = Number(value); if (!Number.isInteger(parsed) || parsed < min || parsed > max) throw new Error(`${label}は${min}～${max}で入力してください`); return parsed; };
const conflict = (expected: unknown, actual: Date) => typeof expected !== "string" || new Date(expected).getTime() !== actual.getTime();
async function audit(req: Request, entityType: string, entityId: string, action: string, beforeData: unknown, afterData: unknown) { await prisma.sparkSharedAuditLog.create({ data: { actorId: uid(req), actorLabel: actorLabel(req), entityType, entityId, action, beforeData: beforeData == null ? undefined : json(beforeData), afterData: afterData == null ? undefined : json(afterData) } }); }
function handle(error: unknown, res: { status: (code: number) => { json: (body: unknown) => void } }, next: (error: unknown) => void) { if (error instanceof Error) { res.status(400).json({ message: error.message }); } else next(error); }

router.get("/availability-periods", async (_req, res, next) => { try { res.json({ periods: await prisma.sparkAvailabilityPeriod.findMany({ orderBy: [{ isActive: "desc" }, { displayLabel: "asc" }] }) }); } catch (e) { next(e); } });
router.post("/availability-periods", async (req, res, next) => { try { const b = req.body as Record<string, unknown>; const kind = String(b.kind); if (!['annual','permanent','irregular'].includes(kind)) throw new Error("排出時期の種別を確認してください"); const displayLabel = parseOptionalText(b.displayLabel, "表示名", 100); if (!displayLabel) throw new Error("表示名を入力してください"); const month = (v: unknown, l: string) => v === null || v === undefined || v === "" ? null : integer(v, 1, 12, l); const part = (v: unknown) => v === null || v === undefined || v === "" ? null : ['early','middle','late'].includes(String(v)) ? String(v) : (() => { throw new Error("時期区分を確認してください"); })(); const period = await prisma.sparkAvailabilityPeriod.create({ data: { kind, displayLabel, startMonth: month(b.startMonth, "開始月"), startPart: part(b.startPart), endMonth: month(b.endMonth, "終了月"), endPart: part(b.endPart), createdById: uid(req), updatedById: uid(req) } }); await audit(req, "availabilityPeriod", period.id, "create", null, period); res.status(201).json({ period, message: "排出時期を登録しました。" }); } catch (e) { handle(e, res, next); } });
router.put("/availability-periods/:id", async (req, res, next) => { try { const before = await prisma.sparkAvailabilityPeriod.findUnique({ where: { id: req.params.id } }); if (!before) { res.status(404).json({ message: "排出時期が見つかりません" }); return; } if (conflict((req.body as Record<string, unknown>).expectedUpdatedAt, before.updatedAt)) { res.status(409).json({ message: "他のユーザーが更新しました。再読み込みしてください" }); return; } const b = req.body as Record<string, unknown>; const displayLabel = parseOptionalText(b.displayLabel, "表示名", 100); if (!displayLabel) throw new Error("表示名を入力してください"); const period = await prisma.sparkAvailabilityPeriod.update({ where: { id: before.id }, data: { displayLabel, isActive: b.isActive !== false, updatedById: uid(req) } }); await audit(req, "availabilityPeriod", period.id, "update", before, period); res.json({ period, message: "排出時期を更新しました。" }); } catch (e) { handle(e, res, next); } });
router.delete("/availability-periods/:id", async (req, res, next) => { try { const before = await prisma.sparkAvailabilityPeriod.findUnique({ where: { id: req.params.id }, include: { _count: { select: { targetLinks: true } } } }); if (!before) { res.status(404).json({ message: "排出時期が見つかりません" }); return; } if (before._count.targetLinks) { res.status(409).json({ message: "使用中のため削除できません。無効化してください" }); return; } await prisma.sparkAvailabilityPeriod.delete({ where: { id: before.id } }); await audit(req, "availabilityPeriod", before.id, "delete", before, null); res.json({ message: "排出時期を削除しました。" }); } catch (e) { next(e); } });

router.get("/event-types", async (_req, res, next) => { try { res.json({ eventTypes: await prisma.sparkRewardEventType.findMany({ orderBy: [{ isActive: "desc" }, { sortOrder: "asc" }] }) }); } catch (e) { next(e); } });
router.post("/event-types", async (req, res, next) => { try { const b = req.body as Record<string, unknown>; const name = parseOptionalText(b.name, "名前", 100); if (!name) throw new Error("名前を入力してください"); const aggregationKind = String(b.aggregationKind); if (!['scheduled','monthlyBaseline'].includes(aggregationKind)) throw new Error("集計種別を確認してください"); const eventType = await prisma.sparkRewardEventType.create({ data: { name, aggregationKind, sortOrder: integer(b.sortOrder ?? 0, 0, 999999, "並び順"), createdById: uid(req), updatedById: uid(req) } }); await audit(req, "rewardEventType", eventType.id, "create", null, eventType); res.status(201).json({ eventType, message: "イベント種別を登録しました。" }); } catch (e) { handle(e, res, next); } });
router.put("/event-types/:id", async (req, res, next) => { try { const before = await prisma.sparkRewardEventType.findUnique({ where: { id: req.params.id } }); if (!before) { res.status(404).json({ message: "イベント種別が見つかりません" }); return; } const b = req.body as Record<string, unknown>; if (conflict(b.expectedUpdatedAt, before.updatedAt)) { res.status(409).json({ message: "他のユーザーが更新しました。再読み込みしてください" }); return; } const name = parseOptionalText(b.name, "名前", 100); if (!name) throw new Error("名前を入力してください"); const eventType = await prisma.sparkRewardEventType.update({ where: { id: before.id }, data: { name, isActive: b.isActive !== false, sortOrder: integer(b.sortOrder ?? before.sortOrder, 0, 999999, "並び順"), updatedById: uid(req) } }); await audit(req, "rewardEventType", eventType.id, "update", before, eventType); res.json({ eventType, message: "イベント種別を更新しました。" }); } catch (e) { handle(e, res, next); } });
router.delete("/event-types/:id", async (req, res, next) => { try { const before = await prisma.sparkRewardEventType.findUnique({ where: { id: req.params.id }, include: { _count: { select: { records: true, schedules: true } } } }); if (!before) { res.status(404).json({ message: "イベント種別が見つかりません" }); return; } if (before._count.records || before._count.schedules) { res.status(409).json({ message: "使用中のため削除できません。無効化してください" }); return; } await prisma.sparkRewardEventType.delete({ where: { id: before.id } }); await audit(req, "rewardEventType", before.id, "delete", before, null); res.json({ message: "イベント種別を削除しました。" }); } catch (e) { next(e); } });

function rewardRecordData(req: Request) { const b = req.body as Record<string, unknown>; const occurrenceName = parseOptionalText(b.occurrenceName, "開催名", 150); if (!occurrenceName) throw new Error("開催名を入力してください"); return { eventTypeId: String(b.eventTypeId), year: integer(b.year, 2000, 2100, "年"), month: integer(b.month, 1, 12, "月"), occurrenceName, startedOn: date(b.startedOn, "開始日", true), crystalCount: integer(b.crystalCount ?? 0, 0, 999999999, "宝晶石"), singleTicketCount: integer(b.singleTicketCount ?? 0, 0, 999999, "単発チケット"), tenPullTicketCount: integer(b.tenPullTicketCount ?? 0, 0, 99999, "10連チケット"), isIncluded: b.isIncluded !== false, evidenceMemo: parseOptionalText(b.evidenceMemo, "根拠メモ", 1000), referenceUrl: parseOptionalText(b.referenceUrl, "参照URL", 2000) }; }
router.get("/records", async (_req, res, next) => { try { res.json({ records: await prisma.sparkRewardRecord.findMany({ include: { eventType: true }, orderBy: [{ year: "desc" }, { month: "desc" }, { updatedAt: "desc" }] }) }); } catch (e) { next(e); } });
router.post("/records", async (req, res, next) => { try { const record = await prisma.sparkRewardRecord.create({ data: { ...rewardRecordData(req), createdById: uid(req), updatedById: uid(req) }, include: { eventType: true } }); await audit(req, "rewardRecord", record.id, "create", null, record); res.status(201).json({ record, message: "獲得実績を登録しました。" }); } catch (e) { handle(e, res, next); } });
router.put("/records/:id", async (req, res, next) => { try { const before = await prisma.sparkRewardRecord.findUnique({ where: { id: req.params.id } }); if (!before) { res.status(404).json({ message: "獲得実績が見つかりません" }); return; } if (conflict((req.body as Record<string, unknown>).expectedUpdatedAt, before.updatedAt)) { res.status(409).json({ message: "他のユーザーが更新しました。再読み込みしてください" }); return; } const record = await prisma.sparkRewardRecord.update({ where: { id: before.id }, data: { ...rewardRecordData(req), updatedById: uid(req) }, include: { eventType: true } }); await audit(req, "rewardRecord", record.id, "update", before, record); res.json({ record, message: "獲得実績を更新しました。" }); } catch (e) { handle(e, res, next); } });
router.delete("/records/:id", async (req, res, next) => { try { const before = await prisma.sparkRewardRecord.findUnique({ where: { id: req.params.id } }); if (!before) { res.status(404).json({ message: "獲得実績が見つかりません" }); return; } await prisma.sparkRewardRecord.delete({ where: { id: before.id } }); await audit(req, "rewardRecord", before.id, "delete", before, null); res.json({ message: "獲得実績を削除しました。" }); } catch (e) { next(e); } });

function scheduleData(req: Request) { const b = req.body as Record<string, unknown>; const name = parseOptionalText(b.name, "開催名", 150); if (!name) throw new Error("開催名を入力してください"); const startedOn = date(b.startedOn, "開始日")!; const endedOn = date(b.endedOn, "終了日", true); if (endedOn && endedOn < startedOn) throw new Error("終了日は開始日以降にしてください"); return { eventTypeId: String(b.eventTypeId), name, startedOn, endedOn, memo: parseOptionalText(b.memo, "メモ", 500) }; }
router.get("/schedules", async (_req, res, next) => { try { res.json({ schedules: await prisma.sparkRewardSchedule.findMany({ include: { eventType: true }, orderBy: { startedOn: "desc" } }) }); } catch (e) { next(e); } });
router.post("/schedules", async (req, res, next) => { try { const schedule = await prisma.sparkRewardSchedule.create({ data: { ...scheduleData(req), createdById: uid(req), updatedById: uid(req) }, include: { eventType: true } }); await audit(req, "rewardSchedule", schedule.id, "create", null, schedule); res.status(201).json({ schedule, message: "開催予定を登録しました。" }); } catch (e) { handle(e, res, next); } });
router.put("/schedules/:id", async (req, res, next) => { try { const before = await prisma.sparkRewardSchedule.findUnique({ where: { id: req.params.id } }); if (!before) { res.status(404).json({ message: "開催予定が見つかりません" }); return; } if (conflict((req.body as Record<string, unknown>).expectedUpdatedAt, before.updatedAt)) { res.status(409).json({ message: "他のユーザーが更新しました。再読み込みしてください" }); return; } const schedule = await prisma.sparkRewardSchedule.update({ where: { id: before.id }, data: { ...scheduleData(req), updatedById: uid(req) }, include: { eventType: true } }); await audit(req, "rewardSchedule", schedule.id, "update", before, schedule); res.json({ schedule, message: "開催予定を更新しました。" }); } catch (e) { handle(e, res, next); } });
router.delete("/schedules/:id", async (req, res, next) => { try { const before = await prisma.sparkRewardSchedule.findUnique({ where: { id: req.params.id } }); if (!before) { res.status(404).json({ message: "開催予定が見つかりません" }); return; } await prisma.sparkRewardSchedule.delete({ where: { id: before.id } }); await audit(req, "rewardSchedule", before.id, "delete", before, null); res.json({ message: "開催予定を削除しました。" }); } catch (e) { next(e); } });

router.put("/month-statuses/:year/:month", async (req, res, next) => { try { const year = integer(req.params.year, 2000, 2100, "年"), month = integer(req.params.month, 1, 12, "月"); const status = await prisma.sparkRewardMonthStatus.upsert({ where: { year_month: { year, month } }, update: { isComplete: Boolean((req.body as Record<string, unknown>).isComplete), updatedById: uid(req) }, create: { year, month, isComplete: Boolean((req.body as Record<string, unknown>).isComplete), updatedById: uid(req) } }); await audit(req, "rewardMonthStatus", status.id, "update", null, status); res.json({ status, message: "集計月を更新しました。" }); } catch (e) { handle(e, res, next); } });

router.get("/summary", async (_req, res, next) => { try { const now = new Date(); const jst = new Date(now.toLocaleString("en-US", { timeZone: "Asia/Tokyo" })); const months = Array.from({ length: 3 }, (_, offset) => { const d = new Date(jst.getFullYear(), jst.getMonth() + offset, 1); return { year: d.getFullYear(), month: d.getMonth() + 1 }; }); const minYear = jst.getFullYear() - 3; const [records, statuses, schedules, eventTypes] = await Promise.all([prisma.sparkRewardRecord.findMany({ where: { isIncluded: true, year: { gte: minYear }, month: { in: months.map((m) => m.month) } }, include: { eventType: true } }), prisma.sparkRewardMonthStatus.findMany({ where: { isComplete: true, year: { gte: minYear } } }), prisma.sparkRewardSchedule.findMany({ where: { startedOn: { gte: new Date(Date.UTC(months[0].year, months[0].month - 1, 1)), lt: new Date(Date.UTC(months[2].year, months[2].month, 1)) } }, include: { eventType: true }, orderBy: { startedOn: "asc" } }), prisma.sparkRewardEventType.findMany({ where: { isActive: true }, orderBy: { sortOrder: "asc" } })]); const complete = new Set(statuses.map((s) => `${s.year}-${s.month}`)); const equivalent = (r: typeof records[number]) => r.crystalCount + r.singleTicketCount * 300 + r.tenPullTicketCount * 3000; const summaries = months.map((target, index) => { const years = [...new Set(records.filter((r) => r.month === target.month && complete.has(`${r.year}-${r.month}`)).map((r) => r.year))].sort((a, b) => b - a).slice(0, 3); const totals = years.map((year) => records.filter((r) => r.year === year && r.month === target.month).reduce((sum, r) => sum + equivalent(r), 0)); const monthSchedules = schedules.filter((s) => s.startedOn.getUTCFullYear() === target.year && s.startedOn.getUTCMonth() + 1 === target.month); const detailedTypes = index === 0 ? eventTypes.filter((type) => type.aggregationKind === "monthlyBaseline" || monthSchedules.some((schedule) => schedule.eventTypeId === type.id)) : []; const ranges = detailedTypes.map((type) => { const values = years.map((year) => records.filter((r) => r.year === year && r.month === target.month && r.eventTypeId === type.id).reduce((sum, r) => sum + equivalent(r), 0)).filter((value) => value > 0); return { id: type.id, name: type.name, eventTypeName: type.name, min: values.length ? Math.min(...values) : null, max: values.length ? Math.max(...values) : null }; }); return { ...target, min: totals.length ? Math.min(...totals) : null, max: totals.length ? Math.max(...totals) : null, records: ranges, schedules: monthSchedules.map((s) => ({ id: s.id, name: s.name, eventTypeName: s.eventType.name, startedOn: s.startedOn.toISOString().slice(0, 10), endedOn: s.endedOn?.toISOString().slice(0, 10) ?? null })) }; }); res.json({ months: summaries }); } catch (e) { next(e); } });

export { router as sparkRewardsRouter };
