import { type FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, type SparkAvailabilityPeriod, type SparkRewardEventType } from "../lib/api";

const now = new Date();
export function SparkReferenceDataPage() {
  const [periods, setPeriods] = useState<SparkAvailabilityPeriod[]>([]); const [eventTypes, setEventTypes] = useState<SparkRewardEventType[]>([]); const [records, setRecords] = useState<Array<Record<string, unknown> & { id: string; occurrenceName: string; year: number; month: number; updatedAt: string; eventType: SparkRewardEventType }>>([]); const [schedules, setSchedules] = useState<Array<Record<string, unknown> & { id: string; name: string; startedOn: string; endedOn: string | null; updatedAt: string; eventType: SparkRewardEventType }>>([]); const [message, setMessage] = useState("");
  const [period, setPeriod] = useState({ displayLabel: "", kind: "annual" }); const [eventType, setEventType] = useState({ name: "", aggregationKind: "scheduled" });
  const [record, setRecord] = useState({ eventTypeId: "", year: now.getFullYear(), month: now.getMonth() + 1, occurrenceName: "", startedOn: "", crystalCount: 0, singleTicketCount: 0, tenPullTicketCount: 0, evidenceMemo: "", referenceUrl: "", isIncluded: true });
  const [schedule, setSchedule] = useState({ eventTypeId: "", name: "", startedOn: "", endedOn: "", memo: "" });
  const load = () => Promise.all([api.sparkAvailabilityPeriods(), api.sparkRewardEventTypes(), api.sparkRewardRecords(), api.sparkRewardSchedules()]).then(([p, e, r, s]) => { setPeriods(p.periods); setEventTypes(e.eventTypes); setRecords(r.records); setSchedules(s.schedules); }); useEffect(() => { void load().catch(showError); }, []);
  const showError = (e: unknown) => setMessage(e instanceof Error ? e.message : "操作に失敗しました"); const done = async (promise: Promise<{ message: string }>) => { try { const result = await promise; setMessage(result.message); await load(); } catch (e) { showError(e); } };
  async function addPeriod(e: FormEvent) { e.preventDefault(); await done(api.createSparkAvailabilityPeriod(period)); setPeriod({ displayLabel: "", kind: "annual" }); }
  async function addEventType(e: FormEvent) { e.preventDefault(); await done(api.createSparkRewardEventType(eventType)); setEventType({ name: "", aggregationKind: "scheduled" }); }
  async function addRecord(e: FormEvent) { e.preventDefault(); await done(api.createSparkRewardRecord({ ...record, startedOn: record.startedOn || null })); setRecord({ ...record, occurrenceName: "", startedOn: "", crystalCount: 0, singleTicketCount: 0, tenPullTicketCount: 0, evidenceMemo: "", referenceUrl: "" }); }
  async function addSchedule(e: FormEvent) { e.preventDefault(); await done(api.createSparkRewardSchedule({ ...schedule, endedOn: schedule.endedOn || null })); setSchedule({ ...schedule, name: "", startedOn: "", endedOn: "", memo: "" }); }
  return <div className="page-stack compact-page spark-reference-page"><section className="page-heading"><div><p className="eyebrow">Shared reference data</p><h1>天井貯金の共有データ</h1><p>全員が編集できます。変更者と変更内容は内部に記録されます。</p></div><Link className="secondary-button" to="/spark-savings?tab=rewards">獲得目安へ戻る</Link></section>{message ? <p className="form-notice">{message}</p> : null}
    <section className="panel"><h2>排出時期マスター</h2><form className="spark-inline-form" onSubmit={addPeriod}><label>種別<select value={period.kind} onChange={(e) => setPeriod({ ...period, kind: e.target.value })}><option value="annual">毎年</option><option value="permanent">恒常</option><option value="irregular">不定期</option></select></label><label>幅を持たせた表示名<input placeholder="例：3月中旬" required value={period.displayLabel} onChange={(e) => setPeriod({ ...period, displayLabel: e.target.value })} /></label><button className="primary-button" type="submit">追加</button></form><SharedList items={periods.map((p) => ({ id: p.id, label: `${p.displayLabel}${p.isActive ? "" : "（無効）"}`, edit: () => { const label = window.prompt("表示名", p.displayLabel); if (label) void done(api.updateSparkAvailabilityPeriod(p.id, { displayLabel: label, isActive: p.isActive, expectedUpdatedAt: p.updatedAt })); }, toggle: () => void done(api.updateSparkAvailabilityPeriod(p.id, { displayLabel: p.displayLabel, isActive: !p.isActive, expectedUpdatedAt: p.updatedAt })), remove: () => void done(api.deleteSparkAvailabilityPeriod(p.id)) }))} /></section>
    <section className="panel"><h2>イベントマスター</h2><form className="spark-inline-form" onSubmit={addEventType}><label>集計種別<select value={eventType.aggregationKind} onChange={(e) => setEventType({ ...eventType, aggregationKind: e.target.value })}><option value="scheduled">開催ごと</option><option value="monthlyBaseline">毎月常設</option></select></label><label>名前<input required value={eventType.name} onChange={(e) => setEventType({ ...eventType, name: e.target.value })} /></label><button className="primary-button" type="submit">追加</button></form><SharedList items={eventTypes.map((t) => ({ id: t.id, label: `${t.name}（${t.aggregationKind === "scheduled" ? "開催ごと" : "毎月常設"}）${t.isActive ? "" : "（無効）"}`, edit: () => { const name = window.prompt("名前", t.name); if (name) void done(api.updateSparkRewardEventType(t.id, { name, isActive: t.isActive, sortOrder: t.sortOrder, expectedUpdatedAt: t.updatedAt })); }, toggle: () => void done(api.updateSparkRewardEventType(t.id, { name: t.name, isActive: !t.isActive, sortOrder: t.sortOrder, expectedUpdatedAt: t.updatedAt })), remove: () => void done(api.deleteSparkRewardEventType(t.id)) }))} /></section>
    <section className="panel"><h2>獲得実績</h2>{!eventTypes.length ? <p className="empty-state">先にイベントマスターを登録してください。</p> : <form className="spark-record-form" onSubmit={addRecord}><EventSelect value={record.eventTypeId} types={eventTypes} change={(eventTypeId) => setRecord({ ...record, eventTypeId })} /><label>年<input min={2000} max={2100} type="number" value={record.year} onChange={(e) => setRecord({ ...record, year: Number(e.target.value) })} /></label><label>月<input min={1} max={12} type="number" value={record.month} onChange={(e) => setRecord({ ...record, month: Number(e.target.value) })} /></label><label>開催名<input required value={record.occurrenceName} onChange={(e) => setRecord({ ...record, occurrenceName: e.target.value })} /></label><label>開始日<input type="date" value={record.startedOn} onChange={(e) => setRecord({ ...record, startedOn: e.target.value })} /></label><label>宝晶石<input min={0} type="number" value={record.crystalCount} onChange={(e) => setRecord({ ...record, crystalCount: Number(e.target.value) })} /></label><label>単発券<input min={0} type="number" value={record.singleTicketCount} onChange={(e) => setRecord({ ...record, singleTicketCount: Number(e.target.value) })} /></label><label>10連券<input min={0} type="number" value={record.tenPullTicketCount} onChange={(e) => setRecord({ ...record, tenPullTicketCount: Number(e.target.value) })} /></label><button className="primary-button" type="submit">追加</button></form>}<SharedList items={records.map((r) => ({ id: r.id, label: `${r.year}年${r.month}月 ${r.eventType.name}：${r.occurrenceName}`, edit: () => { const occurrenceName = window.prompt("開催名", r.occurrenceName); if (occurrenceName) void done(api.updateSparkRewardRecord(r.id, { ...r, occurrenceName, eventTypeId: r.eventType.id, startedOn: typeof r.startedOn === "string" ? r.startedOn.slice(0, 10) : null, expectedUpdatedAt: r.updatedAt })); }, remove: () => void done(api.deleteSparkRewardRecord(r.id)) }))} /></section>
    <section className="panel"><h2>開催予定</h2>{eventTypes.length ? <form className="spark-record-form" onSubmit={addSchedule}><EventSelect value={schedule.eventTypeId} types={eventTypes.filter((t) => t.aggregationKind === "scheduled")} change={(eventTypeId) => setSchedule({ ...schedule, eventTypeId })} /><label>開催名<input required value={schedule.name} onChange={(e) => setSchedule({ ...schedule, name: e.target.value })} /></label><label>開始日<input required type="date" value={schedule.startedOn} onChange={(e) => setSchedule({ ...schedule, startedOn: e.target.value })} /></label><label>終了日<input type="date" value={schedule.endedOn} onChange={(e) => setSchedule({ ...schedule, endedOn: e.target.value })} /></label><button className="primary-button" type="submit">追加</button></form> : null}<SharedList items={schedules.map((s) => ({ id: s.id, label: `${s.startedOn.slice(0, 10)} ${s.eventType.name}：${s.name}`, edit: () => { const name = window.prompt("開催名", s.name); if (name) void done(api.updateSparkRewardSchedule(s.id, { ...s, name, eventTypeId: s.eventType.id, startedOn: s.startedOn.slice(0, 10), endedOn: s.endedOn?.slice(0, 10) ?? null, expectedUpdatedAt: s.updatedAt })); }, remove: () => void done(api.deleteSparkRewardSchedule(s.id)) }))} /></section>
    <section className="panel"><h2>月次集計の完了設定</h2><p>過去月の入力を確認後、その月を集計対象にします。</p><form className="spark-inline-form" onSubmit={(e) => { e.preventDefault(); const form = new FormData(e.currentTarget); void done(api.updateSparkRewardMonthStatus(Number(form.get("year")), Number(form.get("month")), true)); }}><label>年<input defaultValue={now.getFullYear()} max={2100} min={2000} name="year" type="number" /></label><label>月<input defaultValue={now.getMonth() + 1} max={12} min={1} name="month" type="number" /></label><button className="primary-button" type="submit">集計完了にする</button></form></section>
  </div>;
}

function EventSelect({ value, types, change }: { value: string; types: SparkRewardEventType[]; change: (id: string) => void }) { return <label>イベント<select required value={value} onChange={(e) => change(e.target.value)}><option value="">選択</option>{types.filter((t) => t.isActive).map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>; }
function SharedList({ items }: { items: { id: string; label: string; edit?: () => void; toggle?: () => void; remove: () => void }[] }) { return <div className="spark-shared-list">{items.map((item) => <div key={item.id}><span>{item.label}</span><div className="button-row">{item.edit ? <button className="secondary-button" onClick={item.edit} type="button">編集</button> : null}{item.toggle ? <button className="secondary-button" onClick={item.toggle} type="button">有効切替</button> : null}<button className="secondary-button danger-button" onClick={() => { if (window.confirm("削除しますか？")) item.remove(); }} type="button">削除</button></div></div>)}</div>; }
